import { Student, AttendanceRecord, IncomeRecord, ExpenseRecord, UserSession, UserAccount, BimbelSettings, ProspectiveStudent } from '../types';
import { DEFAULT_WA_TEMPLATES } from './whatsapp';

export const DEFAULT_ACCOUNTS: UserAccount[] = [
  {
    role: 'owner',
    id: 'usr-owner-1',
    name: 'Nanik Susilowati, M.Pd',
    username: 'owner',
    password: 'sigma123',
    email: 'owner@bimbelsigma.id',
    phone: '081234567890',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    specialty: 'Pemilik Lembaga & Administrator Utama',
    isActive: true,
    createdAt: '2026-01-01',
  },
  {
    role: 'tutor',
    id: 'usr-tutor-1',
    name: 'Nanik Susilowati, M.Pd',
    username: 'tutor',
    password: 'sigma123',
    email: 'tutor@bimbelsigma.id',
    phone: '085712349988',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    specialty: 'Pengajar Utama & Tutor Pembimbing',
    isActive: true,
    createdAt: '2026-01-05',
  },
  {
    role: 'siswa',
    id: 'usr-std-1',
    name: 'Siswa Bimbel',
    username: 'siswa',
    password: 'sigma123',
    code: 'SISWA',
    phone: '081234567801',
    avatar: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=150&auto=format&fit=crop&q=80',
    specialty: 'Siswa Bimbel',
    isActive: true,
    createdAt: '2026-01-10',
  },
];

export const DEFAULT_USERS: UserSession[] = DEFAULT_ACCOUNTS;

export const DEFAULT_SETTINGS: BimbelSettings = {
  bimbelName: 'RUMAH BELAJAR',
  tagline: 'Belajar Sampai Paham, Bukan Sekadar Hafal',
  ownerName: 'Nanik Susilowati, M.Pd',
  ownerTitle: 'Pemilik & Kepala Lembaga',
  directorTitle: 'Direktur Operasional',
  financeOfficerName: 'Bendahara Bimbel',
  financeOfficerTitle: 'Bendahara / Finance & Admin',
  operationalManagerName: 'Nanik Susilowati, M.Pd',
  operationalManagerTitle: 'Manajer Akademik & Operasional',
  phone: '0812-3456-7890',
  email: 'admin@rumahbelajar.id',
  address: 'Blora, Jawa Tengah',
  city: 'Blora',
  bankInfo: 'BCA: 8830-1234-56 a.n Bimbel',
  systemSalaryCategory: 'Gaji / Honor Tutor',
  systemSppCategory: 'Pembayaran SPP Siswa',
  expenseCategories: [
    'Gaji / Honor Tutor',
    'Sewa Tempat / Gedung',
    'Listrik, Internet & Air',
    'Modul, ATK & Cetak',
    'Marketing / Iklan',
    'Snack & Konsumsi Siswa',
    'Kebersihan & Operasional',
    'Lain-lain',
  ],
  incomeCategories: [
    'Pembayaran SPP Siswa',
    'Biaya Pendaftaran / Registrasi',
    'Modul & Buku Paket',
    'Try Out & Ujian Simulasi',
    'Event / Workshop Bimbel',
    'Lainnya',
  ],
  paymentMethods: [
    'Tunai',
    'Transfer BCA',
    'Transfer Mandiri',
    'Transfer BRI',
    'Transfer BNI',
    'QRIS',
    'GoPay / OVO / Dana',
    'Lainnya',
  ],
  logoUrl: '',
  logoSymbol: 'RB',
  appVersionBadge: 'v2.6 PRO',
  sidebarFooterTitle: 'RUMAH BELAJAR',
  sidebarFooterTagline: '“Belajar Sampai Paham”',
  sidebarFooterNote: 'Data tersimpan aman di Database Cloud & Browser',
  accentColor: 'indigo',

  // Default Pengaturan Dokumen PPDB (Tanpa klaim trial gratis jika tidak dikehendaki)
  ppdbDocSubtitle: 'Penerimaan Peserta Didik Baru & Registrasi Program Bimbingan Belajar',
  ppdbTermsTitle: 'KETENTUAN & PETUNJUK PENDAFTARAN:',
  ppdbTerms: [
    'Lembar ini merupakan bukti sah pendaftaran calon peserta didik baru di Bimbel.',
    'Admin Bimbel akan segera menghubungi orang tua / wali murid melalui WhatsApp untuk konfirmasi pemilihan jadwal dan mata pelajaran.',
    'Penyelesaian administrasi pendaftaran & SPP dilakukan sebelum sesi pembelajaran pertama dimulai.',
    'Siswa yang telah terdaftar resmi akan mendapatkan akses mandiri ke Portal Siswa untuk memantau absensi dan materi belajar.',
  ],

  // Default Pengaturan Pilihan Form PPDB
  ppdbAvailableSubjects: [
    'Matematika',
    'IPA',
    'Bahasa Inggris',
    'Bahasa Indonesia',
    'IPS / PKn',
    'Calistung (Baca, Tulis, Hitung)',
    'Persiapan Ujian Sekolah',
    'Persiapan SNBT / UTBK',
    'Semua Mapel (All-in-One)',
  ],
  ppdbAvailableDays: [
    'Senin',
    'Selasa',
    'Rabu',
    'Kamis',
    'Jumat',
    'Sabtu',
    'Minggu',
  ],
  ppdbAvailableTimeSlots: [
    'Pagi (08:00 - 10:00 WIB)',
    'Siang (13:00 - 15:00 WIB)',
    'Sore 1 (15:30 - 17:00 WIB)',
    'Sore 2 (16:00 - 17:30 WIB)',
    'Malam (18:30 - 20:00 WIB)',
    'Fleksibel / Menyesuaikan',
  ],

  // Default Pengaturan Banner Portal Publik
  portalBannerBadge: 'Pusat Layanan Terpadu Siswa & Calon Siswa Bimbel',
  portalBannerTitle: '',
  portalBannerSubtitle: 'Daftarkan ananda secara online, pantau presensi dan tanggal kehadiran harian, serta cek status iuran les secara transparan kapan saja.',

  ownerDashboardBadge: 'Executive Dashboard (Owner Access)',
  ownerDashboardTitle: '',
  ownerDashboardMessage: 'Pantau metrik finansial, absensi digital real-time, dan pembukuan tahunan dalam satu pintu.',
  tutorDashboardBadge: 'Ruang Kerja Pengajar (Tutor Access)',
  tutorDashboardTitle: '',
  tutorDashboardMessage: 'Fokus pada kualitas pembelajaran: catat absensi harian siswa, topik materi, serta evaluasi pemahaman belajar.',
  studentDashboardBadge: 'Portal Belajar Siswa',
  studentDashboardTitle: '',
  studentDashboardMessage: 'Selamat belajar! Pantau riwayat pertemuan, materi pelajaran, dan absensi belajarmu di sini.',
  loginWelcomeMessage: 'Sistem Manajemen & Presensi Digital Bimbel Terintegrasi',

  // Default Konfigurasi Gaji Tutor
  salaryCalculationMode: 'percentage',
  privatSalaryPercentage: 60, // 60% bagi hasil kelas privat
  groupSalaryPercentage: 40, // 40% bagi hasil kelas grup
  semiPrivatSalaryPercentage: 50, // 50% bagi hasil kelas semi-privat
  minPrivatSessionRate: 50000,
  minGroupSessionRate: 60000,
  flatPrivatSessionRate: 65000,
  flatGroupSessionRate: 80000,
  transportAllowancePerDay: 15000,
  evaluationBonusPerSession: 0,

  // Default Template Pesan WhatsApp
  whatsappTemplates: DEFAULT_WA_TEMPLATES,
};

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'std-01',
    code: 'N0',
    name: 'Naureen Zevania Putri Riansyah',
    level: 'PAUD',
    gradeDetail: 'PAUD / TK',
    classType: 'Privat',
    packageType: 'monthly',
    pricePerSession: 5000,
    monthlyFee: 40000,
    parentName: 'Orang Tua Naureen',
    parentPhone: '081234560001',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Privat PAUD',
  },
  {
    id: 'std-02',
    code: 'K2',
    name: 'Kia',
    level: 'SD',
    gradeDetail: 'Kelas 2 SD',
    classType: 'Grup',
    packageType: 'monthly',
    pricePerSession: 5000,
    monthlyFee: 40000,
    parentName: 'Orang Tua Kia',
    parentPhone: '081234560002',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Grup Kelas 2 SD',
  },
  {
    id: 'std-03',
    code: 'B2',
    name: 'Brian',
    level: 'SD',
    gradeDetail: 'Kelas 2 SD',
    classType: 'Grup',
    packageType: 'monthly',
    pricePerSession: 5000,
    monthlyFee: 40000,
    parentName: 'Orang Tua Brian',
    parentPhone: '081234560003',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Grup Kelas 2 SD',
  },
  {
    id: 'std-04',
    code: 'G2',
    name: 'Gyo',
    level: 'SD',
    gradeDetail: 'Kelas 2 SD',
    classType: 'Grup',
    packageType: 'monthly',
    pricePerSession: 5000,
    monthlyFee: 40000,
    parentName: 'Orang Tua Gyo',
    parentPhone: '081234560004',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Grup Kelas 2 SD',
  },
  {
    id: 'std-05',
    code: 'A3',
    name: 'Abi',
    level: 'SD',
    gradeDetail: 'Kelas 3 SD',
    classType: 'Grup',
    packageType: 'monthly',
    pricePerSession: 5000,
    monthlyFee: 40000,
    parentName: 'Orang Tua Abi',
    parentPhone: '081234560005',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Grup Kelas 3 SD',
  },
  {
    id: 'std-06',
    code: 'S3',
    name: 'Silvia',
    level: 'SD',
    gradeDetail: 'Kelas 3 SD',
    classType: 'Grup',
    packageType: 'monthly',
    pricePerSession: 5000,
    monthlyFee: 40000,
    parentName: 'Orang Tua Silvia',
    parentPhone: '081234560006',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Grup Kelas 3 SD',
  },
  {
    id: 'std-07',
    code: 'G3',
    name: 'Geo',
    level: 'SD',
    gradeDetail: 'Kelas 3 SD',
    classType: 'Grup',
    packageType: 'monthly',
    pricePerSession: 5000,
    monthlyFee: 40000,
    parentName: 'Orang Tua Geo',
    parentPhone: '081234560007',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Grup Kelas 3 SD',
  },
  {
    id: 'std-08',
    code: 'E3',
    name: 'Elvano',
    level: 'SD',
    gradeDetail: 'Kelas 3 SD',
    classType: 'Grup',
    packageType: 'monthly',
    pricePerSession: 5000,
    monthlyFee: 40000,
    parentName: 'Orang Tua Elvano',
    parentPhone: '081234560008',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Grup Kelas 3 SD',
  },
  {
    id: 'std-09',
    code: 'At3',
    name: 'Athar',
    level: 'SD',
    gradeDetail: 'Kelas 3 SD',
    classType: 'Grup',
    packageType: 'monthly',
    pricePerSession: 5000,
    monthlyFee: 40000,
    parentName: 'Orang Tua Athar',
    parentPhone: '081234560009',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Grup Kelas 3 SD',
  },
  {
    id: 'std-10',
    code: 'K4',
    name: 'Kaysa',
    level: 'SD',
    gradeDetail: 'Kelas 4 SD',
    classType: 'Grup',
    packageType: 'monthly',
    pricePerSession: 5000,
    monthlyFee: 40000,
    parentName: 'Orang Tua Kaysa',
    parentPhone: '081234560010',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Grup Kelas 4 SD',
  },
  {
    id: 'std-11',
    code: 'A4',
    name: 'Agan',
    level: 'SD',
    gradeDetail: 'Kelas 4 SD',
    classType: 'Grup',
    packageType: 'monthly',
    pricePerSession: 5000,
    monthlyFee: 40000,
    parentName: 'Orang Tua Agan',
    parentPhone: '081234560011',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Grup Kelas 4 SD',
  },
  {
    id: 'std-12',
    code: 'D4',
    name: 'Dolken',
    level: 'SD',
    gradeDetail: 'Kelas 4 SD',
    classType: 'Grup',
    packageType: 'monthly',
    pricePerSession: 5000,
    monthlyFee: 40000,
    parentName: 'Orang Tua Dolken',
    parentPhone: '081234560012',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Grup Kelas 4 SD',
  },
  {
    id: 'std-13',
    code: 'R4',
    name: 'Rara',
    level: 'SD',
    gradeDetail: 'Kelas 4 SD',
    classType: 'Grup',
    packageType: 'monthly',
    pricePerSession: 5000,
    monthlyFee: 40000,
    parentName: 'Orang Tua Rara',
    parentPhone: '081234560013',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Grup Kelas 4 SD',
  },
  {
    id: 'std-14',
    code: 'KA4',
    name: 'Kaila',
    level: 'SD',
    gradeDetail: 'Kelas 4 SD',
    classType: 'Grup',
    packageType: 'monthly',
    pricePerSession: 5000,
    monthlyFee: 40000,
    parentName: 'Orang Tua Kaila',
    parentPhone: '081234560014',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Grup Kelas 4 SD',
  },
  {
    id: 'std-15',
    code: 'DE4',
    name: 'Debi',
    level: 'SD',
    gradeDetail: 'Kelas 4 SD',
    classType: 'Grup',
    packageType: 'monthly',
    pricePerSession: 5000,
    monthlyFee: 40000,
    parentName: 'Orang Tua Debi',
    parentPhone: '081234560015',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Grup Kelas 4 SD',
  },
  {
    id: 'std-16',
    code: 'T5',
    name: 'Tasya',
    level: 'SD',
    gradeDetail: 'Kelas 5 SD',
    classType: 'Grup',
    packageType: 'monthly',
    pricePerSession: 5000,
    monthlyFee: 40000,
    parentName: 'Orang Tua Tasya',
    parentPhone: '081234560016',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Grup Kelas 5 SD',
  },
  {
    id: 'std-17',
    code: 'B5',
    name: 'Bella',
    level: 'SD',
    gradeDetail: 'Kelas 5 SD',
    classType: 'Grup',
    packageType: 'monthly',
    pricePerSession: 5000,
    monthlyFee: 40000,
    parentName: 'Orang Tua Bella',
    parentPhone: '081234560017',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Grup Kelas 5 SD',
  },
  {
    id: 'std-18',
    code: 'Rj6',
    name: 'Raja',
    level: 'SD',
    gradeDetail: 'Kelas 6 SD',
    classType: 'Grup',
    packageType: 'monthly',
    pricePerSession: 5000,
    monthlyFee: 40000,
    parentName: 'Orang Tua Raja',
    parentPhone: '081234560018',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Grup Kelas 6 SD',
  },
  {
    id: 'std-19',
    code: 'A6',
    name: 'Aura',
    level: 'SD',
    gradeDetail: 'Kelas 6 SD',
    classType: 'Grup',
    packageType: 'monthly',
    pricePerSession: 5000,
    monthlyFee: 40000,
    parentName: 'Orang Tua Aura',
    parentPhone: '081234560019',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Grup Kelas 6 SD',
  },
  {
    id: 'std-20',
    code: 'N6',
    name: 'Naila',
    level: 'SD',
    gradeDetail: 'Kelas 6 SD',
    classType: 'Grup',
    packageType: 'monthly',
    pricePerSession: 5000,
    monthlyFee: 40000,
    parentName: 'Orang Tua Naila',
    parentPhone: '081234560020',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Grup Kelas 6 SD',
  },
  {
    id: 'std-21',
    code: 'Rr6',
    name: 'Rangga',
    level: 'SD',
    gradeDetail: 'Kelas 6 SD',
    classType: 'Grup',
    packageType: 'monthly',
    pricePerSession: 5000,
    monthlyFee: 40000,
    parentName: 'Orang Tua Rangga',
    parentPhone: '081234560021',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Grup Kelas 6 SD',
  },
  {
    id: 'std-22',
    code: 'J6',
    name: 'Juna',
    level: 'SD',
    gradeDetail: 'Kelas 6 SD',
    classType: 'Grup',
    packageType: 'monthly',
    pricePerSession: 5000,
    monthlyFee: 40000,
    parentName: 'Orang Tua Juna',
    parentPhone: '081234560022',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Grup Kelas 6 SD',
  },
  {
    id: 'std-23',
    code: 'Ag6',
    name: 'Agha',
    level: 'SD',
    gradeDetail: 'Kelas 6 SD',
    classType: 'Grup',
    packageType: 'monthly',
    pricePerSession: 5000,
    monthlyFee: 40000,
    parentName: 'Orang Tua Agha',
    parentPhone: '081234560023',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Grup Kelas 6 SD',
  },
  {
    id: 'std-24',
    code: 'Z8',
    name: 'Zidane',
    level: 'SMP',
    gradeDetail: 'Kelas 8 SMP',
    classType: 'Privat',
    packageType: 'monthly',
    pricePerSession: 10000,
    monthlyFee: 80000,
    parentName: 'Orang Tua Zidane',
    parentPhone: '081234560024',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Privat Kelas 8 SMP',
  },
  {
    id: 'std-25',
    code: 'V9',
    name: 'Valen',
    level: 'SMP',
    gradeDetail: 'Kelas 9 SMP',
    classType: 'Grup',
    packageType: 'monthly',
    pricePerSession: 8000,
    monthlyFee: 64000,
    parentName: 'Orang Tua Valen',
    parentPhone: '081234560025',
    address: 'Blora',
    status: 'Aktif',
    joinDate: '2026-01-01',
    tutorName: 'Tutor Bimbel',
    notes: 'Program Grup Kelas 9 SMP',
  },
];

export { INITIAL_ATTENDANCE } from '../data/initialAttendance';

export const INITIAL_INCOMES: IncomeRecord[] = [];

export const INITIAL_EXPENSES: ExpenseRecord[] = [];

export const INITIAL_PROSPECTIVE_STUDENTS: ProspectiveStudent[] = [
  {
    id: 'ppdb-2026-001',
    registrationNumber: 'REG-2026-001',
    studentName: 'Muhammad Rizky Pratama',
    nickname: 'Rizky',
    gender: 'L',
    schoolOrigin: 'SDN 1 Blora',
    level: 'SD',
    gradeDetail: 'Kelas 5 SD',
    classType: 'Privat',
    interestedSubjects: ['Matematika', 'IPA'],
    preferredSchedule: 'Selasa & Jumat (16.00 - 17.30)',
    parentName: 'Hendra Pratama',
    parentPhone: '081234567891',
    address: 'Jl. Pemuda No. 14, Blora',
    notes: 'Ingin persiapan olimpiade matematika SD dan penguatan IPA',
    status: 'Jadwal Trial',
    trialDate: '2026-09-05',
    registrationDate: '2026-09-01',
    createdAt: '2026-09-01T08:30:00Z',
  },
  {
    id: 'ppdb-2026-002',
    registrationNumber: 'REG-2026-002',
    studentName: 'Annisa Rahmadani',
    nickname: 'Nisa',
    gender: 'P',
    schoolOrigin: 'SMPN 2 Blora',
    level: 'SMP',
    gradeDetail: 'Kelas 8 SMP',
    classType: 'Grup',
    interestedSubjects: ['Bahasa Inggris', 'Matematika'],
    preferredSchedule: 'Senin & Kamis (15.30 - 17.00)',
    parentName: 'Siti Rahmawati',
    parentPhone: '085712348899',
    address: 'Perum Taman Asri Blok C2, Blora',
    notes: 'Minat les grup sore bersama teman sekelas',
    status: 'Baru',
    registrationDate: '2026-09-01',
    createdAt: '2026-09-01T09:15:00Z',
  },
];

